### ISSUE TITLE
Clarify what Table.read() / iter() return

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/jsontableschema-js#56]
General well-done on excellent docs!

One clarification requested on https://github.com/frictionlessdata/jsontableschema-js#table

It says:

> iter(callback, failFast, skipConstraints)1,2 - iterate through the given dataset provided in constructor and returns converted data
> read(keyed, extended, limit) - Read part or full source into array of objects if keyed/extended

Not clear:

* Whether this returns array or arrays or array of objects (with objects keyed by header names)
  * (and what keyed/extended does)
* Whether it includes the original header row or whether that is auto-stripped (and how that is determined)

**Comment by roll** [comment]
Thanks! It has to be clarified.

**Comment by rufuspollock** [comment]
@roll and what does `extended` do versus `keyed`?

**Comment by roll** [comment]
@rufuspollock
keyed row - {header1: value1, header2: value2}
extended row - [row_number, headers, values]

**Comment by rufuspollock** [comment]
@roll thanks - definitely something for the docs. I'll try to add. BTW who uses `extended` - i've never seen that format much before.

**Comment by roll** [comment]
@rufuspollock 
It used in many low-level scenarios when you need all information about row from stream but there is no guarantee that is not malformed. For example `goodtables` can't use `keyed` because there is no guarantee that it will not fail - https://github.com/frictionlessdata/goodtables-py/blob/master/goodtables/inspector.py#L205

On high-level it useful when you need to get row + row number. This row number it's exact row number of source stream row. It's not like counted or something. So if you skip first 9 rows first row number from iter(extended=True) will be 10. It's not possible to get this information on client code level using other approach - iter() index in this case will start from 0.

**Comment by rufuspollock** [comment]
@roll more great points. BTW the point about row numbers is why many apps auto-insert an `_id` field. I wonder if we should think about that too for the other options.

It also makes me wonder if we should should a config object here rather than classic parameters and take advantage of ES6 auto-unbundling of config objects ...

PS: I've added your doc info into the README.

**Comment by rufuspollock** [comment]
@roll why don't we have the keyed and extended options for `iter`? And why don't the `iter` options apply to read?

Could we even combine the two functions into called `read` with an extra parameter for doing iter work?

**Comment by roll** [comment]
@rufuspollock 
Added #58

About `read/iter` - it's established pattern in our implementations. For example in some static typed languages will be not possible to have it merged. So for stack consistency it seems good choice. Also it's closer to explicit over implicit rule.

**Comment by rufuspollock** [comment]
@roll makes total sense -- your intuitions are almost always excellent 😄 

I'm going to close this as FIXED as now have #58

**Comment by roll** [comment]
@rufuspollock 
:+1: 

---

CLOSED (#58 extracted)
